# Generated by Django 6.1.1 on 2026-09-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor_nome',
            field=models.CharField(max_length=100),
        ),
    ]
