# Generated by Django 6.1.1 on 2026-09-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_comentario_autor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estados',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Em_Revisao', 'Revisão Editorial'), ('Publicado', 'Publicado!'), ('Rejeitado', 'Rejeitado!!')], default='rascunho', max_length=50),
        ),
    ]
