# Generated by Django 6.1.1 on 2026-09-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_post_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estados',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Em_Revisao', 'Revisão Editorial'), ('Publicado', 'Publicado!'), ('Rejeitado', 'Rejeitado!!')], default='Rascunho', max_length=50),
        ),
    ]
